# Site
title:              Kimcoding's Dev Note!
author:             Kimcoding
bio:                Blog is incomplete. Click <a href="https://blog.naver.com/junghun1997">https://blog.naver.com/junghun1997</a>
description:        "umm..."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/profile.webp'
background:         #'assets/img/wallpaper.webp'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://kimcodingvv.github.io
  #http://localhost:4000/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname: kimcoding

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-159984814-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              junghun1997@naver.com
#twitter:            username
#facebook:           username
github-url:         kimcodingvv
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          kimcodingvv
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
soundcloud:         kimcoding
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  #- jekyll-bootstrap-sass
#bootstrap:
#   assets: true

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, .idea]
